name: GitHub Readme Stats
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:
jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: teoxoy/profile-readme-stats@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
